model_name: deepseek-chat
api_key: sk-0161f83279f34eba9f8d01fa17034265
#api_key: sk-94097fdffc774f86a33652da50fb397f
api_url: https://api.deepseek.com
max_tokens: 4096
timeout: 60
temperature: 0.2
model_type: LLMModel