model_name: llama3.1-8b
#api_key: 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
api_key: LA-ebaf80d7816e484dab0dfa026b556e34968b2ddc000646f19133811879f23622
api_url: https://api.llama-api.com
max_tokens: 4096
timeout: 300
temperature: 0.2
model_type: LLMModel