eval:
  num_matches: 10
  output_path: ./output/o1-mini/werewolf/scene1/o1-mini_vs_gpt-4o-mini
  weave_prj_name: eval_o1-mini_werewolf_scene1_o1-mini_vs_gpt-4o-mini
game:
  game_name: WereWolfEnv
  good_model_config: o1-mini.yaml
  bad_model_config: gpt-4o-mini.yaml
agent:
- agent_name: WereWolfAgent
  agent_nick: Seer
  agent_model: LLMModel
  agent_model_config: o1-mini.yaml
- agent_name: WereWolfAgent
  agent_nick: Doctor
  agent_model: LLMModel
  agent_model_config: o1-mini.yaml
- agent_name: WereWolfAgent
  agent_nick: Villager
  agent_model: LLMModel
  agent_model_config: o1-mini.yaml
- agent_name: WereWolfAgent
  agent_nick: Villager
  agent_model: LLMModel
  agent_model_config: o1-mini.yaml
- agent_name: WereWolfAgent
  agent_nick: Villager
  agent_model: LLMModel
  agent_model_config: o1-mini.yaml
- agent_name: WereWolfAgent
  agent_nick: Villager
  agent_model: LLMModel
  agent_model_config: o1-mini.yaml
- agent_name: WereWolfAgent
  agent_nick: Werewolf
  agent_model: LLMModel
  agent_model_config: gpt-4o-mini.yaml
- agent_name: WereWolfAgent
  agent_nick: Werewolf
  agent_model: LLMModel
  agent_model_config: gpt-4o-mini.yaml
