agent:
- agent_model: LLMModel
  agent_model_config: GPT-4o.yaml
  agent_model_config_opp: gpt-4o-mini.yaml
  agent_model_opp: LLMModel
  agent_name: StreetFight3Agent
  agent_prompt: StreetFight3Prompt
  agent_prompt_opp: StreetFight3Prompt
eval:
  num_matches: 10
  output_path: ./output/GPT-4o/streetfight3/scene2/GPT-4o_vs_gpt-4o-mini_asyFalse
  weave_prj_name: eval_GPT-4o_streetfight3_scene2_GPT-4o_vs_gpt-4o-mini_asyFalse
game:
  asynch_mode: false
  game_mode: agent_vs_agent
  game_name: StreetFight3Env
