agent:
- agent_model: LLMModel
  agent_model_config: gemini-15-flash.yaml
  agent_model_config_opp: gpt-4o-mini.yaml
  agent_model_opp: LLMModel
  agent_name: StrategoAgent
  agent_prompt: StategoPrompt
  agent_prompt_opp: StategoPrompt
eval:
  num_matches: 10
  output_path: ./output/gemini-15-flash/stratego/scene1/gemini-15-flash_vs_gpt-4o-mini_random
  weave_prj_name: eval_gemini-15-flash_stratego_scene1_gemini-15-flash_vs_gpt-4o-mini_random
game:
  game_init: random
  game_mode: agent_vs_agent
  game_name: StrategoMultiAgentEnv
