eval:
  num_matches: 10
  output_path: ./output/llama31-8b/welfare_diplomacy/scene1/llama31-8b_vs_gpt-4o-mini
  weave_prj_name: eval_llama31-8b_welfare_diplomacy_scene1_llama31-8b_vs_gpt-4o-mini
game:
  game_name: WelfareDiplomacyEnv
  game_map: standard_welfare
  game_base_agent_model: random
  game_max_message_rounds: 3
  game_max_years: 10
  game_early_stop_max_years: 0
  game_exploiter_powers: Austria,England,France,Germany
  game_exploiter_model: llama31-8b.yaml
  game_super_exploiter_powers: Italy,Russia,Turkey
  game_super_exploiter_model: gpt-4o-mini.yaml
  game_summarizer_model: LLMModel
  game_summarizer_model_config: deepseek-v25.yaml
  RL_unit_threshold: 10
  RL_center_threshold: 10
agent:
- agent_name: WDAgent
  agent_power: Austria
  agent_mode_name: exploiter
  agent_model: LLMModel
  agent_model_config: llama31-8b.yaml
- agent_name: WDAgent
  agent_power: England
  agent_mode_name: exploiter
  agent_model: LLMModel
  agent_model_config: llama31-8b.yaml
- agent_name: WDAgent
  agent_power: France
  agent_mode_name: exploiter
  agent_model: LLMModel
  agent_model_config: llama31-8b.yaml
- agent_name: WDAgent
  agent_power: Germany
  agent_mode_name: exploiter
  agent_model: LLMModel
  agent_model_config: llama31-8b.yaml
- agent_name: WDAgent
  agent_power: Italy
  agent_mode_name: exploiter
  agent_model: LLMModel
  agent_model_config: gpt-4o-mini.yaml
- agent_name: WDAgent
  agent_power: Russia
  agent_mode_name: exploiter
  agent_model: LLMModel
  agent_model_config: gpt-4o-mini.yaml
- agent_name: WDAgent
  agent_power: Turkey
  agent_mode_name: exploiter
  agent_model: LLMModel
  agent_model_config: gpt-4o-mini.yaml
