eval:
  num_matches: 10
  output_path: ./output/gpt-35-turbo-0125/werewolf/scene1/gpt-35-turbo-0125_vs_gpt-4o-mini
  weave_prj_name: eval_gpt-35-turbo-0125_werewolf_scene1_gpt-35-turbo-0125_vs_gpt-4o-mini
game:
  game_name: WereWolfEnv
  good_model_config: gpt-35-turbo-0125.yaml
  bad_model_config: gpt-4o-mini.yaml
agent:
- agent_name: WereWolfAgent
  agent_nick: Seer
  agent_model: LLMModel
  agent_model_config: gpt-35-turbo-0125.yaml
- agent_name: WereWolfAgent
  agent_nick: Doctor
  agent_model: LLMModel
  agent_model_config: gpt-35-turbo-0125.yaml
- agent_name: WereWolfAgent
  agent_nick: Villager
  agent_model: LLMModel
  agent_model_config: gpt-35-turbo-0125.yaml
- agent_name: WereWolfAgent
  agent_nick: Villager
  agent_model: LLMModel
  agent_model_config: gpt-35-turbo-0125.yaml
- agent_name: WereWolfAgent
  agent_nick: Villager
  agent_model: LLMModel
  agent_model_config: gpt-35-turbo-0125.yaml
- agent_name: WereWolfAgent
  agent_nick: Villager
  agent_model: LLMModel
  agent_model_config: gpt-35-turbo-0125.yaml
- agent_name: WereWolfAgent
  agent_nick: Werewolf
  agent_model: LLMModel
  agent_model_config: gpt-4o-mini.yaml
- agent_name: WereWolfAgent
  agent_nick: Werewolf
  agent_model: LLMModel
  agent_model_config: gpt-4o-mini.yaml
