game:
  game_name: AgentVSComputerStarcraftEnv
  game_map: Ancient Cistern LE
  players: Protoss_VS_Protoss
  game_difficulty: medium
  game_ai_build: macro
  asynch_mode: true
agent:
- agent_name: GPTAgent
  agent_model: LLMModel
  agent_model_config: deepseek-v25.yaml
  agent_prompt: StarCraftIIPrompt_V4
eval:
  num_matches: 5
  output_path: ./output/deepseek-v25/starcraft2/scene2/deepseek-v25_vs_computer_macro_asyTrue
  weave_prj_name: eval_deepseek-v25_starcraft2_scene2_agent_vs_computer_macro_asyTrue
