agent:
- agent_model: LLMModel
  agent_model_config: gpt-35-turbo-0125.yaml
  agent_model_config_opp: gpt-4o-mini.yaml
  agent_model_opp: LLMModel
  agent_name: StrategoAgent
  agent_prompt: StategoPrompt
  agent_prompt_opp: StategoPrompt
eval:
  num_matches: 10
  output_path: ./output/gpt-35-turbo-0125/stratego/scene2/gpt-35-turbo-0125_vs_gpt-4o-mini_fixed
  weave_prj_name: eval_gpt-35-turbo-0125_stratego_scene2_gpt-35-turbo-0125_vs_gpt-4o-mini_fixed
game:
  game_init: fixed
  game_mode: agent_vs_agent
  game_name: StrategoMultiAgentEnv
