game:
  game_name: AgentVSComputerStarcraftEnv
  game_map: Ancient Cistern LE
  players: Protoss_VS_Protoss
  game_difficulty: medium
  game_ai_build: macro
  asynch_mode: true
agent:
- agent_name: GPTAgent
  agent_model: LLMModel
  agent_model_config: o1-mini.yaml
  agent_prompt: StarCraftIIPrompt_V4
eval:
  num_matches: 5
  output_path: ./output/o1-mini/starcraft2/scene2/o1-mini_vs_computer_macro_asyTrue
  weave_prj_name: eval_o1-mini_starcraft2_scene2_agent_vs_computer_macro_asyTrue
