agent:
- agent_embedding_api_key: sk-sufonZ4mNq9h9SDq7e311aA6C31c40A1BaB5369481D96cFf
  agent_embedding_api_url: https://api.openai.com
  agent_embedding_model_name: text-embedding-ada-002
  agent_model: LLMModel
  agent_model_config: llama31-8b.yaml
  agent_name: MastabaAgent
  pinecone_key: 4dc46cc0-9dda-4049-aeab-cfc2962ae192
eval:
  num_matches: 10
  output_path: ./output/llama31-8b/civ/scene1/llama31-8b_run_myagent_T1_WORLDSMALL
  weave_prj_name: eval_llama31-8b_civ_scene1_agent_run_myagent_T1_WORLDSMALL
game:
  game_map: myagent_T1_WORLDSMALL
  game_name: CivEnv
  game_turn: 400
