agent:
- agent_model: LLMModel
  agent_model_config: o1-mini.yaml
  agent_model_config_opp: gpt-4o-mini.yaml
  agent_model_opp: LLMModel
  agent_name: StrategoAgent
  agent_prompt: StategoPrompt
  agent_prompt_opp: StategoPrompt
eval:
  num_matches: 10
  output_path: ./output/o1-mini/stratego/scene2/o1-mini_vs_gpt-4o-mini_fixed
  weave_prj_name: eval_o1-mini_stratego_scene2_o1-mini_vs_gpt-4o-mini_fixed
game:
  game_init: fixed
  game_mode: agent_vs_agent
  game_name: StrategoMultiAgentEnv
