
eval:
  num_matches: 10
  output_path: ./output/stratego/o1mini_vs_agent_gpt4omini_fixed
  weave_prj_name: GT-MindEval-stratego-o1mini_vs_agent_gpt4omini_fixed

game:
  game_name: StrategoMultiAgentEnv
  game_mode: agent_vs_agent
  game_init: fixed

agent:
  -
    agent_name: StrategoAgent
    agent_model: LLMModel
    agent_model_config: o1-mini.yaml
    agent_prompt: StategoPrompt

    agent_model_opp: LLMModel
    agent_model_config_opp: gpt-4o-mini.yaml
    agent_prompt_opp: StategoPrompt