game:
  game_name: AgentVSComputerStarcraftEnv
  game_map: Ancient Cistern LE
  players: Protoss_VS_Protoss
  game_difficulty: medium
  game_ai_build: rush
  asynch_mode: true
agent:
- agent_name: GPTAgent
  agent_model: LLMModel
  agent_model_config: gpt-35-turbo-0125.yaml
  agent_prompt: StarCraftIIPrompt_V4
eval:
  num_matches: 5
  output_path: ./output/gpt-35-turbo-0125/starcraft2/scene4/gpt-35-turbo-0125_vs_computer_rush_asyTrue
  weave_prj_name: eval_gpt-35-turbo-0125_starcraft2_scene4_agent_vs_computer_rush_asyTrue
