agent:
- agent_model: LLMModel
  agent_model_config: gemini-15-flash.yaml
  agent_model_config_opp: gpt-4o-mini.yaml
  agent_model_opp: LLMModel
  agent_name: StreetFight3Agent
  agent_prompt: StreetFight3Prompt
  agent_prompt_opp: StreetFight3Prompt
eval:
  num_matches: 10
  output_path: ./output/gemini-15-flash/streetfight3/scene1/gemini-15-flash_vs_gpt-4o-mini_asyTrue
  weave_prj_name: eval_gemini-15-flash_streetfight3_scene1_gemini-15-flash_vs_gpt-4o-mini_asyTrue
game:
  asynch_mode: true
  game_mode: agent_vs_agent
  game_name: StreetFight3Env
