eval:
  num_matches: 10
  output_path: ./output/gemini-15-flash/werewolf/scene1/gemini-15-flash_vs_gpt-4o-mini
  weave_prj_name: eval_gemini-15-flash_werewolf_scene1_gemini-15-flash_vs_gpt-4o-mini
game:
  game_name: WereWolfEnv
  good_model_config: gemini-15-flash.yaml
  bad_model_config: gpt-4o-mini.yaml
agent:
- agent_name: WereWolfAgent
  agent_nick: Seer
  agent_model: LLMModel
  agent_model_config: gemini-15-flash.yaml
- agent_name: WereWolfAgent
  agent_nick: Doctor
  agent_model: LLMModel
  agent_model_config: gemini-15-flash.yaml
- agent_name: WereWolfAgent
  agent_nick: Villager
  agent_model: LLMModel
  agent_model_config: gemini-15-flash.yaml
- agent_name: WereWolfAgent
  agent_nick: Villager
  agent_model: LLMModel
  agent_model_config: gemini-15-flash.yaml
- agent_name: WereWolfAgent
  agent_nick: Villager
  agent_model: LLMModel
  agent_model_config: gemini-15-flash.yaml
- agent_name: WereWolfAgent
  agent_nick: Villager
  agent_model: LLMModel
  agent_model_config: gemini-15-flash.yaml
- agent_name: WereWolfAgent
  agent_nick: Werewolf
  agent_model: LLMModel
  agent_model_config: gpt-4o-mini.yaml
- agent_name: WereWolfAgent
  agent_nick: Werewolf
  agent_model: LLMModel
  agent_model_config: gpt-4o-mini.yaml
