agent:
- agent_model: LLMModel
  agent_model_config: llama31-70b.yaml
  agent_model_config_opp: gpt-4o-mini.yaml
  agent_model_opp: LLMModel
  agent_name: StreetFight3Agent
  agent_prompt: StreetFight3Prompt
  agent_prompt_opp: StreetFight3Prompt
eval:
  num_matches: 10
  output_path: ./output/llama31-70b/streetfight3/scene1/llama31-70b_vs_gpt-4o-mini_asyTrue
  weave_prj_name: eval_llama31-70b_streetfight3_scene1_llama31-70b_vs_gpt-4o-mini_asyTrue
game:
  asynch_mode: true
  game_mode: agent_vs_agent
  game_name: StreetFight3Env
